### ISSUE TITLE
Unexpected HTTP/1.x request: OPTIONS 

### ISSUE THREAD

**Issue by minhdtb** [improbable-eng/ts-protoc-gen#134]
Hello

I'm using grpc-java as backend and ReactJS as front end

Everything seems fine until I try to run

I have got unexpected error

`io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: OPTIONS /com.minhdtb.demo.protos.Greeter/SayHello 
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314) ~[netty-codec-http2-4.1.29.Final.jar:4.1.29.Final]
...`

My client code

`
const client = new GreeterClient("http://localhost:6565");

const request = new HelloRequest();

request.setTest1("xxxx nha");

client.sayHello(request, (error, responseMessage) => {    });
`

Please help?

**Comment by minhdtb** [comment]
I have had resolved this issue by using Envoy proxy. Thanks

**Comment by clehene** [comment]
@minhdtb shouldn't this work with gRPC directly?
