### ISSUE TITLE
 Argument of type 'typeof MyService' is not assignable to parameter of type 'ServiceDefinition<...>'

### ISSUE THREAD

**Issue by EvanDarwin** [improbable-eng/ts-protoc-gen#141]
### The Issue
I'm trying to set up my first gRPC server using ts-protoc-gen, and I can't seem to get the `server.addService()` call to work properly. I can import everything and it compiles just fine, but I think the types might be incompatible with some version of protobuf I'm running.

**Package Versions**
> ts-protoc-gen@0.8.0
> grpc@1.17.0-pre1
> protobufjs@5.0.3

**TypeScript Compile Error**
```
$ ts-node ./src/index.ts

/mnt/c/.../node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts(22,23): error TS2345: Argument of type 'typeof BarcodeService' is not assignable to parameter of type 'ServiceDefinition<{ GetBarcode: () => undefined; CreateBarco
de: () => undefined; }>'.
  Types of property 'GetBarcode' are incompatible.
    Type 'BarcodeServiceGetBarcode' is missing the following properties from type 'MethodDefinition<any, any>': path, requestSerialize, responseSerialize, requestDeserialize, r
esponseDeserialize

    at createTSError (/mnt/c/.../project/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/mnt/c/.../project/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/mnt/c/.../project/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/mnt/c/.../project/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/c/.../project/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
error Command failed with exit code 1.
```

### Code
**index.ts**
```ts
import grpc from "grpc";
import Barcode from "./proto_gen/barcode_pb_service";

function main() {
    const server = new grpc.Server();
    server.addService(Barcode.BarcodeService, {
        GetBarcode: () => undefined,
        CreateBarcode: () => undefined,
    });
    server.bind('0.0.0.0:4200', grpc.ServerCredentials.createInsecure());
    server.start();
}

if (require.main === module) {
    main();
}
```

****

**barcode.proto**
```protobuf
syntax = "proto3";
package mypackage;

///// SERVICES
service BarcodeService {
    rpc GetBarcode(GetBarcodeRequest) returns (GetBarcodeResponse);
    rpc CreateBarcode(CreateBarcodeRequest) returns (CreateBarcodeResponse);
}

///// ENUMS
enum BarcodeType { ... }

///// RESPONSES
message GetBarcodeResponse {
    uint32 id = 1;
    uint64 barcode = 2;
    BarcodeType type = 3;
    uint64 created_at = 4;
}

message CreateBarcodeResponse {
    bool success = 1;
    uint32 id = 2;
}

///// REQUESTS
message GetBarcodeRequest {
    uint32 id = 1;
    uint64 _audit_source_id = 100;
}

message CreateBarcodeRequest {
    uint64 barcode = 1;
    uint64 _audit_source_id = 100;
}
```

**Comment by boatengyeboah** [comment]
Same here, is this resolved?

**Comment by boatengyeboah** [comment]
@EvanDarwin I think their protoc plugin only generates client code but not server code. So if you want to build a grpc server in typescript use https://www.npmjs.com/package/grpc_tools_node_protoc_ts

**Comment by jonny-improbable** [comment]
@boatengyeboah is correct, The Services that ts-protoc-gen generates are only for use with https://github.com/improbable-eng/grpc-web.
