### ISSUE TITLE
protoc command fails with: Error: Cannot find module 'google-protobuf/google/protobuf/descriptor_pb' when used with NodeJS 12.x

### ISSUE THREAD

**Issue by ronak2121** [improbable-eng/ts-protoc-gen#261]
**Versions of relevant software used**

- ts-protoc-gen version 0.14.0
- protoc version 3.9.1
- google-protobuf version 3.6.0

**What happened**

I'm trying to upgrade the NodeJS version I compile my code against (NodeJS 8.x) with the version we actually run with (NodeJS 12.x), but this plugin is currently blocking me.

**What you expected to happen**

The compiler working just fine with Node 12.x, since NodeJS 8.x is already EOL.

**How to reproduce it (as minimally and precisely as possible)**:

Compile any protobuf schema within a NodeJS 12.x environment.

**Full logs to relevant components**

Error: Cannot find module 'google-protobuf/google/protobuf/descriptor_pb'
Require stack:
- NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/ts/message.js
- NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/ts/fileDescriptorTSD.js
- NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/index.js
- NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/bin/protoc-gen-ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/ts/message.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/ts/message.js',
    'NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/ts/fileDescriptorTSD.js',
    'NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/lib/index.js',
    'NodeJS-ts-protoc-gen/NodeJS-ts-protoc-gen-0.14.x.2.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/commonjs/ts-protoc-gen/bin/protoc-gen-ts'
  ]
}

**Comment by ronak2121** [comment]
Never mind I figured this out. It's an artifact to differences in module resolution between NodeJS 12.x and 8.x.
